modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/Norbiros/emojitype/issues"
displayURL = "https://modrinth.com/mod/emoji-type"
updateJSONURL="https://api.modrinth.com/updates/emoji-type/forge_updates.json?neoforge=only"
logoFile = "logo.png"
logoBlur = false
authors = "Cyborgcabbage,Norbiros"

[[mods]]
modId = "emojitype"
version = "${version}"
displayName = "Emoji Type"
description='''
A mod that lets you type minecraft emojis easier!
'''
credits="Thanks to cyborgcabbage for original mod!"

[[mixins]]
config = "emojitype-common.mixins.json"

[[dependencies.emojitype]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.emojitype]]
modId = "cloth_config"
type = "optional"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"